name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup Deno
        uses: denoland/setup-deno@v1.3.0
        with:
          deno-version: v1.46.0

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Publish package
        run: deno publish

      - name: Create tag
        run: deno run --allow-run .github/workflows/create_git_tag.ts

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "Automated release for version ${{ github.ref }}"
          draft: false
          prerelease: false
